using MockBankApi.Models;
using System.Net;

namespace MockBankApi.Services
{
    public class AccountService : IAccountService
    {


        List<Staging> Accounts = new List<Staging>
            {
                new Staging { Id =  1 ,
                 AccountNumber  = "1590572512",
                 AccountName = "Tomiloba Maryam",
                 Address = "3 Fair View Appartment, Dolphin Estate",
                 City = "Ikoyi",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5075.00,
                CreatedAt  = new DateTime(2022, 01, 01)
    },
                  new Staging { Id =  2,
                 AccountNumber  = "3121784323",
                 AccountName = "Jadesola Ehigiator",
                 Address = "Shop 53 Block C, Mabushi Altra Modern Market",
                 City = "Mabushi",
                State = "Abuja",
                Currency = "Naira",
                CumulativeInflow = 502300.00,
                CreatedAt  = new DateTime(2022, 01, 01)
                },
                   new Staging { Id =  3 ,
                 AccountNumber  = "0405772257",
                 AccountName = "Ireti Osuagwu",
                 Address = "1649A,4th Avenue",
                 City = "Festac Town",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 0.00,
                CreatedAt  = new DateTime(2022, 01, 01)

                },
                   new Staging { Id =  4 ,
                 AccountNumber  = "2080766748",
                 AccountName = "Adeboye Nojeem",
                 Address = "Akanbi Adeniran Street,Oko Oba",
                  City = "Agege",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 700.00,
                CreatedAt  = new DateTime(2022, 01, 01)
                },
                  new Staging { Id =  5,
                 AccountNumber  = "07247533310",
                 AccountName = "Ebiowei Adewura",
                 Address = " Block C, Ultra Modern Market, Garki Ii",
                  City = "Fct",
                State = "Abuja",
                Currency = "Naira",
                CumulativeInflow = 2.00,
                CreatedAt  = new DateTime(2022, 01, 01)
                },
                   new Staging { Id =  6 ,
                 AccountNumber  = "3121234079",
                 AccountName = "Abisola Saheed",
                 Address = "5, Ifelodun Street",
                  City = "Olugbode Town",
                State = "  Ibadan South West",
                Currency = "Naira",
                CumulativeInflow = 400.00,
                CreatedAt  = new DateTime(2022, 01, 01)
                },
                   new Staging { Id =  7 ,
                 AccountNumber  = "0405171001",
                 AccountName = "Kayode Obianuju",
                 Address = "3 Boye Street",
                  City = "Oshodi",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5000,
                CreatedAt  = new DateTime(2022, 01, 01)

                },
                 new Staging { Id =  8 ,
                 AccountNumber  = "2080125745",
                 AccountName = "Tope Oyelude",
                 Address = " 3 Nworgu St Rumuomasi",
                  City = "Port Harcourt",
                State = "Rivers",
                Currency = "Naira",
                CumulativeInflow = 5000,
                CreatedAt  = new DateTime(2022, 01, 01)
                },
                  new Staging { Id =  9 ,
                 AccountNumber  = "0724829293",
                 AccountName = "Adewale Ayuba",
                 Address = "Sokode Crescent, Zone 5, Wuse",
                  City = "Fct",
                State = " Abuja",
                Currency = "Naira",
                CumulativeInflow = 500000,
                CreatedAt  = new DateTime(2022, 12, 31),
                },
                  new Staging { Id =  10 ,
                 AccountNumber  = "7900572512",
                 AccountName = "Ado Gwanja",
                 Address = "6 oshodi drive, Penisual Graden Estate",
                 City = "Ikoyi",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 700005.00,
                CreatedAt  = new DateTime(2023, 01, 01),

    },

                new Staging { Id =  11 ,
                 AccountNumber  = "1110572512",
                 AccountName = "Andre Blaze",
                 Address = "3, Coperative Estate",
                 City = "Ajah",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5075.00,
                CreatedAt  = new DateTime(2023, 12, 31)
    },
                  new Staging { Id =  12,
                 AccountNumber  = "2221784323",
                 AccountName = "Bella Shmurda",
                 Address = "3 Alhaja Humuani Memorial Mall, Kudirat Abiola Road",
                  City = "Ikeja",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 6300.00,
                        CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  13 ,
                 AccountNumber  = "0405712257",
                 AccountName = "Martins Okechukwu",
                 Address = "1749A,10th Avenue",
                 City = "Festac Town",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 0.00,
                 CreatedAt  = new DateTime(2022, 01, 01)
                },
                   new Staging { Id =  14 ,
                 AccountNumber  = "2027766748",
                 AccountName = "Dammy Krane",
                 Address = "3  Adeniran Street,Oko Oba",
                  City = "Agege",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 700.00,
                 CreatedAt  = new DateTime(2022, 01, 01)
                },
                  new Staging { Id =  15,
                 AccountNumber  = "07247532210",
                 AccountName = "Omotola Jalade",
                 Address = "1 Markunjola Street Orile Lagos Lagos Island Orile",
                  City = "Ajah",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 2.00,
                CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  16 ,
                 AccountNumber  = "1121234079",
                 AccountName = "Obiora Nwokolobia-Agu",
                 Address = "7, Iyawo treet",
                  City = "Olugbode Town",
                State = "  Ibadan South West",
                Currency = "Naira",
                CumulativeInflow = 400.00,
                       CreatedAt  = new DateTime(2022, 01, 01)
                },
                   new Staging { Id =  17 ,
                 AccountNumber  = "0405122001",
                 AccountName = "Patrick Nnaemeka",
                 Address = "3, patrick Wow Estate",
                  City = "Ajah",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5000,
                          CreatedAt  = new DateTime(2022, 01, 01)
                },
                 new Staging { Id =  18 ,
                 AccountNumber  = "0080125745",
                 AccountName = " Victor Okolie",
                 Address = " Idumota, 110 Nnamdi Azikwe St",
                  City = " Lagos Island",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5000,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                  new Staging { Id =  19 ,
                 AccountNumber  = "0722829293",
                 AccountName = "Dairo James",
                 Address = "Sokode Crescent, Zone 5, Wuse",
                  City = "Fct",
                State = " Abuja",
                Currency = "Naira",
                CumulativeInflow = 5000,
                         CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  20 ,
                 AccountNumber  = "0724829273",
                 AccountName = "John Dairo",
                 Address = "Sokode Crescent, Zone 5, Wuse",
                  City = "Fct",
                State = " Abuja",
                Currency = "Naira",
                CumulativeInflow = 5000,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                     new Staging { Id =  21 ,
                 AccountNumber  = "1590534512",
                 AccountName = "Oyindamola Daniel",
                 Address = "3 Osker Estano street",
                 City = "Badore",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5075.00,
                CreatedAt  = new DateTime(2015, 12, 31),

    },

                new Staging { Id =  22 ,
                 AccountNumber  = "1590572982",
                 AccountName = "Johnson Emmanuel",
                 Address = "3 Chief fuji st, Ijegun",
                 City = "Ijegun",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5075.00,
                CreatedAt  = new DateTime(2015, 12, 31)
    },
                  new Staging { Id =  23,
                 AccountNumber  = "3121184323",
                 AccountName = "Helen Epega",
                 Address = "No 5, Plot 1439 Sanusi Fafunwa Str, Opp Karimu Kotun Str",
                  City = "Victoria Island",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 502300.00,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  24 ,
                 AccountNumber  = "0405772557",
                 AccountName = "Okechukwu Justice",
                 Address = "1749A,5th Avenue",
                 City = "Festac Town",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 0.00,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  25 ,
                 AccountNumber  = "2080116748",
                 AccountName = "Teria Yarhere",
                 Address = "3 Light house, Lekki",
                  City = "Lekki",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 700.00,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                  new Staging { Id =  26,
                 AccountNumber  = "07242533310",
                 AccountName = "Jalade Ekeinde ",
                 Address = "Suite 17, Ground Floor, Richway Plaza, 112 Broad St",
                  City = "Fct",
                State = "Abuja",
                Currency = "Naira",
                CumulativeInflow = 2.00,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  27 ,
                 AccountNumber  = "3221234079",
                 AccountName = "Oliver Sunday",
                 Address = "10, Chief Ayo Adebi Street",
                  City = "Olugbode Town",
                State = "  Ibadan South West",
                Currency = "Naira",
                CumulativeInflow = 400.00,
                   CreatedAt  = new DateTime(2022, 01, 01)
                },
                   new Staging { Id =  28 ,
                 AccountNumber  = "140517221",
                 AccountName = "Okorie Gift",
                 Address = "15 Coperative Estate",
                  City = "Badore",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5000,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                 new Staging { Id =  29 ,
                 AccountNumber  = "2080122245",
                 AccountName = "Efosa Okolie",
                 Address = "17 Campbell St, Lagos Island 102273",
                  City = " Lagos Island",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5000,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                  new Staging { Id =  30 ,
                 AccountNumber  = "0721829293",
                 AccountName = "Kent Clack",
                 Address = "Sokode Crescent, Zone 5, Wuse",
                  City = "Fct",
                State = " Abuja",
                Currency = "Naira",
                CumulativeInflow = 5000,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  31 ,
                 AccountNumber  = "0724821393",
                 AccountName = "Adeyoyin Osubu",
                 Address = "Sokode Crescent, Zone 5, Wuse",
                  City = "Fct",
                State = " Abuja",
                Currency = "Naira",
                CumulativeInflow = 5000,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                     new Staging { Id =  32 ,
                 AccountNumber  = "1590200512",
                 AccountName = "Elohor Eva Alordiah",
                 Address = " B17, Shagari Quaters",
                 City = "Gombe",
                State = "Gombe",
                Currency = "Naira",
                CumulativeInflow = 5075.00,
                CreatedAt  = new DateTime(20, 12, 31)
    },
                  new Staging { Id =  33,
                 AccountNumber  = "3121724323",
                 AccountName = "Adefolahan John",
                 Address = "12, Golden Plaza, Awolowo Road",
                  City = "Mabushi",
                State = "Ikoyi",
                Currency = "Lagos",
                CumulativeInflow = 502300.00,
                   CreatedAt  = new DateTime(2022, 01, 01)
                },
                   new Staging { Id =  34,
                 AccountNumber  = "0405772217",
                 AccountName = "Oluwatobiloba Daniel",
                 Address = "Suite 35-38, Sebuff Plaza, Osapa",
                 City = "Festac Town",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 0.00,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  35,
                 AccountNumber  = "2080766758",
                 AccountName = "Omorinmade Kuti",
                 Address = " F9 Lagos City Mall, opp. Muson Center",
                  City = "Lagos Island",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 700.00,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                  new Staging { Id =  36,
                 AccountNumber  = "07247533311",
                 AccountName = "Oritsefemi Majemite",
                 Address = " Block D, Garki Ii",
                  City = "Fct",
                State = "Abuja",
                Currency = "Naira",
                CumulativeInflow = 2.00,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  37,
                 AccountNumber  = "3121234559",
                 AccountName = "Akanite Saheed",
                 Address = "7, Ifelodun Street",
                  City = "Olugbode Town",
                State = "  Ibadan South West",
                Currency = "Naira",
                CumulativeInflow = 400.00,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  38 ,
                 AccountNumber  = "04051757601",
                 AccountName = "Samuel Peters",
                 Address = "13 Dolphin Estate",
                  City = "Ajah",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5000,
                   CreatedAt  = new DateTime(2023, 01, 01)
                },
                 new Staging { Id =  39,
                 AccountNumber  = "2080125445",
                 AccountName = "Okolie Prince",
                 Address = "1st/2nd Floor winner's plaza, 17 Balogun St, Lagos Island",
                  City = "Lagos Island",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5000,
                   CreatedAt  = new DateTime(2021, 01, 01)
                },
                  new Staging { Id =  40,
                 AccountNumber  = "0724829483",
                 AccountName = "Peter King",
                 Address = "Sokode Crescent, Zone 5, Wuse",
                  City = "Fct",
                State = " Abuja",
                Currency = "Naira",
                CumulativeInflow = 5000,
                   CreatedAt  = new DateTime(2022, 01, 01)
                },
                  new Staging { Id =  41,
                 AccountNumber  = "1590572513",
                 AccountName = "Echezonachukwu Nduka ",
                 Address = "5 ,Zik Avenue",
                 City = " Abakaliki",
                State = " Ebonyi",
                Currency = "Naira",
                CumulativeInflow = 5075.00,
                CreatedAt  = new DateTime(2021, 01, 01)
    },

                new Staging { Id =  42,
                 AccountNumber  = "1590571112",
                 AccountName = "Fireboy DML",
                 Address = "4 lafiaji drive",
                 City = "Ikoyi",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5075.00,

                CreatedAt  = new DateTime(2021, 01, 01)
    },
                  new Staging { Id =  43,
                 AccountNumber  = "3121784319",
                 AccountName = "Jayne Isibor",
                 Address = "1, Hussey Street",
                  City = "Yaba",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 502300.00,
                CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  44 ,
                 AccountNumber  = "0405772251",
                 AccountName = "Daniel Anidugbe",
                 Address = "3 Iriri road",
                 City = "Benin",
                State = "Edo",
                Currency = "Naira",
                CumulativeInflow = 0.00,
                CreatedAt  = new DateTime(2022, 01, 01)
                },
                   new Staging { Id =  45,
                 AccountNumber  = "2080356748",
                 AccountName = "Adewale Mayowa",
                 Address = "35 Diamond Lane island",
                  City = "Agege",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 700.00
                },
                  new Staging { Id =  46,
                 AccountNumber  = "07247533110",
                 AccountName = " Ekele Etim",
                 Address = "6 Hamzer Street",
                  City = "Fct",
                State = "Abuja",
                Currency = "Naira",
                CumulativeInflow = 2.00        ,
                CreatedAt  = new DateTime(2022, 01, 01)
                 },
                   new Staging { Id =  47 ,
                 AccountNumber  = "3221234079",
                 AccountName = "Abisola Jude",
                 Address = "13, Adeola Odeku St",
                  City = "Olugbode Town",
                State = "  Ibadan South West",
                Currency = "Naira",
                CumulativeInflow = 400.00,           
                CreatedAt  = new DateTime(2022, 01, 01)
          },
                   new Staging { Id =  48,
                 AccountNumber  = "0405171111",
                 AccountName = "Devan Aigbe",
                 Address = "33, Black Gate Estate",
                  City = "Ajah",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5000,
                CreatedAt  = new DateTime(2023, 01, 01)
                },
                 new Staging { Id =  49 ,
                 AccountNumber  = "2080135745",
                 AccountName = "Tobechukwu Friday",
                 Address = " 5 Nworgu St Rumuomasi",
                  City = "Port Harcourt",
                State = "Rivers",
                Currency = "Naira",
                CumulativeInflow = 5000,
                      CreatedAt  = new DateTime(2022, 01, 01)
                },
                  new Staging { Id =  50 ,
                 AccountNumber  = "0724829103",
                 AccountName = "King Adeyoyin",
                 Address = "Sokode Crescent, Zone 5, Wuse",
                  City = "Fct",
                State = " Abuja",
                Currency = "Naira",
                CumulativeInflow = 5000,
                       CreatedAt  = new DateTime(2022, 01, 01)
                },
                   new Staging { Id =  51 ,
                 AccountNumber  = "0722229293",
                 AccountName = "Adeyoyin Olasunkanmi",
                 Address = "Sokode Crescent, Zone 5, Wuse",
                  City = "Fct",
                State = " Abuja",
                Currency = "Naira",
                CumulativeInflow = 5000,
                 CreatedAt  = new DateTime(2023, 01, 01)
                },
                     new Staging { Id =  52 ,
                 AccountNumber  = "1590572111",
                 AccountName = "Adedamola Oyinlola",
                 Address = "Suite 172, All Seasons' Place",
                 City = "Ojodu-Berger",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5075.00,
                CreatedAt  = new DateTime(2021, 12, 31)
    },

                new Staging { Id =  53 ,
                 AccountNumber  = "1200572512",
                 AccountName = "Tomiloba Ade Kemi",
                 Address = "10, Christ the king Estate",
                 City = "Ikoyi",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 5088.00,
                CreatedAt  = new DateTime(2021, 12, 31)
    },
                  new Staging { Id =  54,
                 AccountNumber  = "0021784323",
                 AccountName = "Jade Solari",
                 Address = "Shop 49 Block C, Mabushi Altra Modern Market",
                  City = "Mabushi",
                State = "Abuja",
                Currency = "Naira",
                CumulativeInflow = 2000.00,
                CreatedAt  = new DateTime(2022, 01, 01),
                },
                   new Staging { Id =  55,
                 AccountNumber  = "0005772257",
                 AccountName = "Kingsley Chinweike",
                 Address = "1649A,7th Avenue",
                 City = "Festac Town",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 1000,
                CreatedAt  = new DateTime(2023, 01, 01),
                },
                   new Staging { Id =  60,
                 AccountNumber  = "2031766748",
                 AccountName = "Mayowa Emmanuel ",
                 Address = " Igbosere Rd, Lagos Island 102273",
                  City = "Lagos",
                State = "Lagos",
                Currency = "Naira",
                CumulativeInflow = 750.00,
                CreatedAt  = new DateTime(2022, 01, 01),
                },
                  new Staging { Id =  61,
                 AccountNumber  = "07247533321",
                 AccountName = "Zamani Ekele",
                 Address = " 4 Mussa way, GRA",
                  City = "Fct",
                State = "Abuja",
                Currency = "Naira",
                CumulativeInflow = 2.00,
                CreatedAt  = new DateTime(2023, 01, 01)
                },
                   new Staging { Id =  62,
                 AccountNumber  = "3121234179",
                 AccountName = " Akanite Jhon",
                 Address = "11, Biodun Street",
                  City = "Olugbode Town",
                State = "  Ibadan South West",
                Currency = "Naira",
                CumulativeInflow = 400.00,
                CreatedAt  = new DateTime(2023, 01, 01),
                },
                   new Staging { Id =  63 ,
                 AccountNumber  = "0405181001",
                 AccountName = "Akoji Daniel",
                 Address = "20, Jude Walter Drive",
                  City = "Ogarah",
                State = "Delta",
                Currency = "Naira",
                CumulativeInflow = 600,
                CreatedAt  = new DateTime(2023, 01, 01),
                },
                 new Staging { Id =  64 ,
                 AccountNumber  = "2080235745",
                 AccountName = "Sunday",
                 Address = " 15 Chisom Akinzua St Rumuomasi",
                  City = "Port Harcourt",
                State = "Rivers",
                Currency = "Naira",
                CumulativeInflow = 400,
                CreatedAt  = new DateTime(2023, 01, 01),
                },
                  new Staging { Id =  65 ,
                 AccountNumber  = "0724329293",
                 AccountName = "Bankole Abel",
                 Address = "Sokode Crescent, Zone 8, Wuse",
                  City = "Fct",
                State = " Abuja",
                Currency = "Naira",
                CumulativeInflow = 50000,
                 CreatedAt  = new DateTime(2023, 01, 01),
                },
                   new Staging { Id =  66 ,
                 AccountNumber  = "1234829293",
                 AccountName = "John terry",
                 Address = "Sokode Crescent, Zone 4, Wuse",
                  City = "Fct",
                State = " Abuja",
                Currency = "Naira",
                CumulativeInflow = 50,
                  CreatedAt  = new DateTime(2023, 01, 01),
                },


            };
        public List<Staging> GetAccountService(AccountDateParameter daterange)
        {
            var results = Accounts.Where(x => x.CreatedAt >= daterange.StartDate && x.CreatedAt <= daterange.EndDate).ToList();
            return results;
        }

        public Staging GetAccountById(int stagingId)
        {
            return Accounts.FirstOrDefault(x => x.Id == stagingId);
        }
    }
}
